spring:
  datasource:
    name: dream
    #    url: jdbc:mysql://10.10.1.113:3306/dream?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/dream?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.hao.**.bean
